#!/bin/bash -el

# Copyright 2016 tsuru authors. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

SOURCE_DIR=/var/lib/tsuru

source ${SOURCE_DIR}/base/rc/config
source ${SOURCE_DIR}/base/deploy

set +e
test -e ${CURRENT_DIR}/Caddyfile && sudo mv ${CURRENT_DIR}/Caddyfile /etc/Caddyfile
set -e

if [ -f ${CURRENT_DIR}/requirements.sh ]; then
	sh ${CURRENT_DIR}/requirements.sh
fi
